// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE

async function injectDeps(deps) {
	return await new Promise((resolve, reject) => {
		if (!Array.isArray(deps)) {
			deps = [deps];
		}
		window.dojoDynamicRequire(deps, function () { resolve(Array.from(arguments)) });
	});
}
// END EXTRA CODE

/**
 * @param {string} containerId
 * @returns {Promise.<void>}
 */
export async function Render(containerId) {
	// BEGIN USER CODE
	const container = document.querySelector('#' + containerId);

	if (container.innerHTML == '') {

		//首次渲染
		const [html] = await injectDeps('dojo/html');
		html.set(container, `
		<div id="luckysheet" style="margin:0px;padding:0px;position:absolute;width:100%;height:100%;left: 0px;top: 0px;">
    </div>
		`);

		// According to the browser language
		var lang = mx.session.sessionData.locale.code.split('_')[0];
		var options = {
			container: 'luckysheet',
			lang: lang,
			// pager: {
			// 	pageIndex: 1,
			// 	pageSize: 10,
			// 	total: 50,
			// 	selectOption: [10, 20]
			// },
			forceCalculation: false,
			fontList: [
				{
					"fontName": "HanaleiFill",
					"url": "resources/luckysheet/assets/iconfont/HanaleiFill-Regular.ttf"
				},
				{
					"fontName": "Anton",
					"url": "resources/luckysheet/assets/iconfont/Anton-Regular.ttf"
				},
				{
					"fontName": "Pacifico",
					"url": "resources/luckysheet/assets/iconfont/Pacifico-Regular.ttf"
				}
			],
			hook: {
				cellDragStop: function (cell, postion, sheetFile, ctx, event) {
					// console.info(cell, postion, sheetFile, ctx, event);
				},
				rowTitleCellRenderBefore: function (rowNum, postion, ctx) {
					// console.log(rowNum);
				},
				rowTitleCellRenderAfter: function (rowNum, postion, ctx) {
					// console.log(ctx);
				},
				columnTitleCellRenderBefore: function (columnAbc, postion, ctx) {
					// console.log(columnAbc);
				},
				columnTitleCellRenderAfter: function (columnAbc, postion, ctx) {
					// console.log(postion);
				},
				cellRenderBefore: function (cell, postion, sheetFile, ctx) {
					// console.log(cell,postion,sheetFile,ctx);
				},
				cellRenderAfter: function (cell, postion, sheetFile, ctx) {
					// console.log(postion);
				},
				cellMousedownBefore: function (cell, postion, sheetFile, ctx) {
					// console.log(postion);
				},
				cellMousedown: function (cell, postion, sheetFile, ctx) {
					// console.log(sheetFile);
				},
				sheetMousemove: function (cell, postion, sheetFile, moveState, ctx) {
					// console.log(cell,postion,sheetFile,moveState,ctx);
				},
				sheetMouseup: function (cell, postion, sheetFile, moveState, ctx) {
					// console.log(cell,postion,sheetFile,moveState,ctx);
				},
				cellAllRenderBefore: function (data, sheetFile, ctx) {
					// console.info(data,sheetFile,ctx)
				},
				updated: function (operate) {
					// console.info(operate)
				},
				cellUpdateBefore: function (r, c, value, isRefresh) {
					// console.info('cellUpdateBefore',r,c,value,isRefresh)
				},
				cellUpdated: function (r, c, oldValue, newValue, isRefresh) {
					// console.info('cellUpdated',r,c,oldValue, newValue, isRefresh)
				},
				sheetActivate: function (index, isPivotInitial, isNewSheet) {
					// console.info(index, isPivotInitial, isNewSheet)
				},
				rangeSelect: function (index, sheet) {
					// console.info(index, sheet)
				},
				commentInsertBefore: function (r, c) {
					// console.info(r, c)
				},
				commentInsertAfter: function (r, c, cell) {
					// console.info(r, c, cell)
				},
				commentDeleteBefore: function (r, c, cell) {
					// console.info(r, c, cell)
				},
				commentDeleteAfter: function (r, c, cell) {
					// console.info(r, c, cell)
				},
				commentUpdateBefore: function (r, c, value) {
					// console.info(r, c, value)
				},
				commentUpdateAfter: function (r, c, oldCell, newCell) {
					// console.info(r, c, oldCell, newCell)
				},
				cellEditBefore: function (range) {
					// console.info(range)
				},
				workbookCreateAfter: function (json) {
					// console.info(json)
				},
				rangePasteBefore: function (range, data) {
					// console.info('rangePasteBefore',range,data)
					// return false; //Can intercept paste
				},


			},
		}

		options.loading = {
			image: () => {
				return `<svg viewBox="25 25 50 50" class="circular">
					<circle cx="50" cy="50" r="20" fill="none"></circle>
					</svg>`
			},
			imageClass: "loadingAnimation"
		}
		options.cellRightClickConfig = {
			customs: [{
				title: 'test',
				onClick: function (clickEvent, event, params) {
					console.log('function test click', clickEvent, event, params)
				}
			}]
		}
		luckysheet.create(options);
	} else {

	}
	// END USER CODE
}
